baseURL   = "https://blobosle.com/blog/"
publishDir = "../blog"
languageCode = 'en-us'
title = 'A non-ergodic blog'
theme = "hugo-theme-monochrome"
canonifyURLs  = true
relativeURLs  = false

[outputs]
  home = ["HTML","RSS","JSON"]

[params]
  navbar_title = "~/blog"
  footer = "© 2025 Benjamin Lobos Lertpunyaroj"
  enable_site_search = true


[[menu.navbar]]
  identifier = "posts"
  name = "./posts"
  url = "/posts/"
  weight = 1

[[menu.navbar]]
  identifier = "purdue"
  name = "./purdue"
  url = "/purdue/"
  weight = 2

[[menu.navbar]]
  identifier = "showcase"
  name = "~/showcase"
  url = "https://blobosle.com/showcase/"
  weight = 3
